name: Fullstack Project
on: [push]
jobs:
    Backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            -   uses: actions/checkout@v3
            -   name: install .net sdk
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 7.0.x
            -   name: install all dependencies
                run: dotnet restore
            -   name: build the project
                run: dotnet build
    Frontend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js 19.x
                uses: actions/setup-node@v3
                with:
                    node-version: 19.x
                    cache: 'npm'
                    cache-dependency-path: package-lock.json
            -   run: npm ci
            -   name: Install dependencies
                run: npm install 
            -   name: Build file
                run: npm run build